import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'
import { ThemeProvider }  from '@/contexts/ThemeContext'
import { PointsProvider } from '@/contexts/PointsContext'
import ServiceWorkerRegistration from '@/components/ServiceWorkerRegistration'
import InstallPrompt from '@/components/ui/InstallPrompt'
import { Analytics }     from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'


const jakarta = Plus_Jakarta_Sans({
  subsets:  ['latin'],
  variable: '--font-jakarta',
  weight:   ['400', '500', '600', '700', '800'],
  display:  'swap',
})

// iPhone launch screens. iOS ignores the manifest's background_color and shows
// white without these. Generated by public/icons/make_icons.py (navy + logo,
// matching the Android splash and the in-app launch splash).
const IOS_STARTUP_IMAGES = [
  { url: '/icons/splash/apple-splash-1320x2868.png', media: '(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1206x2622.png', media: '(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1290x2796.png', media: '(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1179x2556.png', media: '(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1284x2778.png', media: '(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1170x2532.png', media: '(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1125x2436.png', media: '(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1242x2688.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-828x1792.png', media: '(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-1242x2208.png', media: '(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-750x1334.png', media: '(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
  { url: '/icons/splash/apple-splash-640x1136.png', media: '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)' },
]

export const metadata = {
  title:       'ExamPrep A1',
  description: 'Prepare for WAEC and JAMB with confidence',
  manifest:    '/manifest.json',
  appleWebApp: {
    capable:         true,
    statusBarStyle:  'black-translucent',
    title:           'ExamPrep A1',
    startupImage:    IOS_STARTUP_IMAGES,
  },
  icons: {
    icon: [
      { url: '/icons/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/icons/favicon-48.png', sizes: '48x48', type: 'image/png' },
      { url: '/icons/icon-192.png',   sizes: '192x192', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
}


export const viewport = {
  // Navy while the app launches (matches the splash). Once the first screen is
  // ready, lib/themeColor.js switches it to the canvas colour for the theme.
  themeColor:    '#062A78',
  width:         'device-width',
  initialScale:  1,
  maximumScale:  1,
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jakarta.variable} suppressHydrationWarning>
      <head>
        {/*
          Prevent flash of wrong theme: runs synchronously before first paint,
          before React hydrates. A plain <script> in <head> is the correct
          App Router pattern for this — next/script is not needed and causes
          a React warning with Turbopack when used for inline beforeInteractive.
        */}
        <script
          dangerouslySetInnerHTML={{ __html: `(function(){try{var s=localStorage.getItem('ep-theme');var d=s?s==='dark':window.matchMedia('(prefers-color-scheme: dark)').matches;if(d)document.documentElement.classList.add('dark');}catch(e){}})();` }}
        />
        {/*
          Launch splash: when the installed app opens on /student or /onboarding,
          show the navy brand screen from the very first frame (styles in
          globals.css). lib/launchSplash.js fades it out when the first screen
          is ready (after at least 2.5 s); the 6 s timer here is a safety net.
        */}
        <script
          dangerouslySetInnerHTML={{ __html: `(function(){try{var h=document.documentElement,p=location.pathname;var app=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;if(app&&(p.indexOf('/student')===0||p.indexOf('/onboarding')===0)){h.classList.add('ep-launching');setTimeout(function(){h.classList.remove('ep-launching','ep-launch-out')},6000)}}catch(e){}})();` }}
        />
        <link rel="preload" as="image" href="/icons/launch-splash.webp" type="image/webp" />
        {/*
          Catch the browser's one-time install offer before React hydrates.
          It often fires early; without this, Install buttons miss it.
          lib/pwaInstall.js reads it from window.__epInstallPrompt.
        */}
        <script
          dangerouslySetInnerHTML={{ __html: `window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();window.__epInstallPrompt=e;window.dispatchEvent(new Event('ep:installprompt'))});` }}
        />
      </head>
      <body className="font-jakarta antialiased bg-base text-primary">
        {/*
          ServiceWorkerRegistration is a 'use client' component that registers
          the SW via useEffect — the correct App Router pattern, no next/script needed.
        */}
        <ServiceWorkerRegistration />
        <InstallPrompt />
        <Analytics />
        <SpeedInsights />
        <ThemeProvider>
          {/*
            PointsProvider lives here so XP is available to any part of the app.
            The student/layout.js also wraps in PointsProvider — React dedupes
            context providers, so the inner one (student) shadows the outer one
            for student pages. Non-student pages (admin, onboarding) get the
            outer provider with a zero default, which is fine.
          */}
          <PointsProvider>
            {children}
          </PointsProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}